- name: Tools
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - screen
    - tmux
    - vim
    - tree

- name: Default editor
  become: true
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: $ansible_env.HOME/.vim/bundle/Vundle.vim

- name: Personnal vim configuration
  file:
    state: link
    src: "{{ role_path }}/files/home/vimrc"
    dest: $ansible_env.HOME/.vimrc

- name: Personnal bash configuration
  blockinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    marker: "# ANSIBLE MANAGED BLOCK : {mark} : bash profile"
    block: "source {{ lookup('env', 'HOME') }}/system-config/roles/ansible.cli/files/home/bash.profile"
