- name: Tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - screen
    - tmux
    - vim
    - tree

- name: Default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /home/{{ username }}/.vim/bundle/Vundle.vim

- name: Personnal vim configuration
  file:
    state: link
    src: /home/{{ username }}/system-config/roles/ansible.cli/files/home/vimrc
    dest: /home/{{ username }}/.vimrc

- name: Personnal bash configuration
  blockinfile:
    dest: /home/{{ username }}/.bashrc
    block: source /home/{{ username }}/system-config/roles/ansible.cli/files/home/bash_profile
